# -*- coding: utf-8 -*-
"""AI Emotion Detector Using Text ,Image and voice 2026

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TdZJiKrWLWQWWCtHhwhJuP14StRaJmGU
"""

!pip install transformers torch torchvision torchaudio
!pip install opencv-python fer librosa soundfile gradio numpy pillow

import torch
import numpy as np
import librosa
import gradio as gr

# ===============================================
# 🧠 Emotion Detector
# Text + Image + RAVDESS Voice + Login + Drive (FIXED)
# ===============================================

# --- STEP 1: INSTALL ---
!pip install -q transformers torch deepface tf-keras opencv-python Pillow gradio librosa soundfile scikit-learn joblib

# --- STEP 2: IMPORTS ---
import torch
import numpy as np
import librosa
import os
import joblib
from datetime import datetime
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline
from deepface import DeepFace
import gradio as gr

# --- STEP 3: GOOGLE DRIVE ---
from google.colab import drive
drive.mount('/content/drive')

BASE_PATH = "/content/drive/MyDrive/EmotionDetector"

TEXT_PATH = f"{BASE_PATH}/text"
IMAGE_PATH = f"{BASE_PATH}/image"
AUDIO_PATH = f"{BASE_PATH}/audio"

os.makedirs(TEXT_PATH, exist_ok=True)
os.makedirs(IMAGE_PATH, exist_ok=True)
os.makedirs(AUDIO_PATH, exist_ok=True)
# --- STEP 4: LOGIN (UPDATED WITH USER TRACKING) ---
def login(user, password, state):
    if user and password:
        state = user
        return gr.update(visible=False), gr.update(visible=True), state
    return gr.update(visible=True), gr.update(visible=False), state
# --- STEP 5: BETTER TEXT MODEL ---

text_classifier = pipeline(
    "text-classification",
    model="j-hartmann/emotion-english-distilroberta-base",
    top_k=None
)

# --- STEP 7: LOAD CREMA-D / RAVDESS MODEL SAFELY ---

RAVDESS_MODEL_PATH = "/content/drive/MyDrive/RAVDESS/model.pkl"
RAVDESS_ENCODER_PATH = "/content/drive/MyDrive/RAVDESS/encoder.pkl"

print("🔄 Loading Audio Emotion Model...")

if os.path.exists(RAVDESS_MODEL_PATH) and os.path.exists(RAVDESS_ENCODER_PATH):
    model = joblib.load(RAVDESS_MODEL_PATH)
    encoder = joblib.load(RAVDESS_ENCODER_PATH)
    print("✅ Audio Model Loaded Successfully")
else:
    model = None
    encoder = None
    print("⚠️ Audio Model NOT found - fallback mode enabled")


# --- STEP 8: AUDIO FEATURE EXTRACTION ---
def extract_audio_features(file):
    audio, sr = librosa.load(file, duration=3, offset=0.5)
    mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=40)
    return np.mean(mfcc.T, axis=0)
    #----STEP 9 SAVE FUNCTION -----
def save_to_drive(tab, result, state):
    time = datetime.now().strftime("%Y%m%d_%H%M%S")

    username = state if isinstance(state, str) else getattr(state, "value", "unknown")

    content = f"User: {username}\nTime: {time}\nResult:\n{result}\n"

    if tab == "text":
        path = f"{TEXT_PATH}/text_{time}.txt"
    elif tab == "image":
        path = f"{IMAGE_PATH}/image_{time}.txt"
    else:
        path = f"{AUDIO_PATH}/audio_{time}.txt"

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
# --- STEP 10: TEXT ---
def analyze_text_emotion(text):
    if not text.strip():
        return "Please enter text."

    try:
        results = text_classifier(text)[0]

        results = sorted(results, key=lambda x: x['score'], reverse=True)

        output = ""
        for item in results[:5]:
            output += f"{item['label']}: {item['score']:.3f}\n"

        save_to_drive("text", output, "user")
        return output

    except Exception as e:
        return f"Text Error: {str(e)}"

# --- STEP 11: IMAGE ---
def analyze_image_emotion(image):
    if image is None:
        return "Please upload image."

    try:
        temp_path = "/content/temp_img.jpg"
        image.save(temp_path)

        result = DeepFace.analyze(
            img_path=temp_path,
            actions=['emotion'],
            enforce_detection=False
        )

        emotions = result[0]["emotion"]

        sorted_emotions = sorted(
            emotions.items(),
            key=lambda x: x[1],
            reverse=True
        )

        output = ""
        for emotion, score in sorted_emotions[:5]:
            output += f"{emotion}: {score:.2f}\n"

        save_to_drive("image", output, "user")
        return output

    except Exception as e:
        return f"Image Error: {str(e)}"
#STEP 12 CREMA-D FIX----
# --- STEP 12: AUDIO (FIXED 8 EMOTIONS + SCORING) ---

RAVDESS_LABELS = [
    "neutral",
    "calm",
    "happy",
    "sad",
    "angry",
    "fearful",
    "disgust",
    "surprised"
]

def analyze_audio_emotion(audio_file):
    if audio_file is None:
        return "Please upload audio."

    try:
        features = extract_audio_features(audio_file)
        features = np.array(features).reshape(1, -1)

        # =========================
        # ✅ TRAINED MODEL MODE
        # =========================
        if model is not None and encoder is not None:
            probs = model.predict_proba(features)[0]

            results = sorted(
                [(encoder.inverse_transform([i])[0], float(p)) for i, p in enumerate(probs)],
                key=lambda x: x[1],
                reverse=True
            )

        # =========================
        # ❌ FALLBACK MODE (IMPROVED)
        # =========================
        else:
            f = features.flatten()

            # simple heuristic scoring (more stable than energy-only)
            scores = {
                "angry": np.mean(f[:5]),
                "happy": np.mean(f[5:10]),
                "sad": np.mean(f[10:15]),
                "neutral": np.mean(f[15:20]),
                "fearful": np.mean(f[20:25]),
                "disgust": np.mean(f[25:30]),
                "surprised": np.mean(f[30:35]),
                "calm": np.mean(f[35:40])
            }

            total = sum(abs(v) for v in scores.values())
            results = [(k, abs(v)/total if total != 0 else 0.12) for k, v in scores.items()]
            results = sorted(results, key=lambda x: x[1], reverse=True)

        # =========================
        # OUTPUT FORMAT
        # =========================
        output = "🎧 Audio Emotion Prediction Results:\n"
        for emo, score in results[:8]:
            output += f"{emo.upper()}: {score:.2f}\n"

        save_to_drive("audio", output, "user")
        return output

    except Exception as e:
        return f"Audio Error: {str(e)}"
# --- STEP 13: UI ---
with gr.Blocks() as demo:

    login_box = gr.Column(visible=True)
    app_box = gr.Column(visible=False)

    with login_box:
        gr.Markdown("## 🔐 Login Panel")
        user = gr.Textbox(label="Username")
        pwd = gr.Textbox(label="Password", type="password")
        btn = gr.Button("Login")

    user_state = gr.State("")

    with app_box:
        gr.Markdown("# 🧠 Multimodal Emotion Detector")

        with gr.Tabs():

            with gr.Tab("Text"):
                t_in = gr.Textbox(lines=4, label="Input Text", scale=2)
                t_out = gr.Textbox(label="Result", lines=6, interactive=False, scale=3)
                gr.Button("Analyze").click(analyze_text_emotion, t_in, t_out)

            with gr.Tab("Image"):
                i_in = gr.Image(type="pil")
                i_out = gr.Textbox(label="Result", lines=6, scale=3)
                gr.Button("Analyze").click(analyze_image_emotion, i_in, i_out)

            with gr.Tab("Voice"):
                a_in = gr.Audio(type="filepath")
                a_out = gr.Textbox(label="Result", lines=6, scale=3)
                gr.Button("Analyze").click(analyze_audio_emotion, a_in, a_out)

    btn.click(login, [user, pwd, user_state], [login_box, app_box, user_state])

demo.launch(share=True)